// Load formatLineSpacing + formatDocument directly from extension.js
const src = require('fs').readFileSync(__dirname + '/../extension.js', 'utf8');
const fnStart = src.indexOf('function formatLineSpacing');
const fnEnd   = src.indexOf('function getCompilerPath');
eval(src.slice(fnStart, fnEnd));

const TEST = [
    'class Animal',
    'init(name,age)',
    'self.name=name',
    'end',
    'speak()',
    'return self.name',
    'end',
    'async fetchBio(id)',
    'let data=await api.get(id)',
    'return data',
    'end',
    'toString()',
    'return "hello"',
    'end',
    'end',
    '',
    'class Dog is Animal',
    'speak()',
    'return self.name+" barks!"',
    'end',
    'async fetchBreed(id)',
    'let info=await db.query(id)',
    'return info.breed',
    'end',
    'end',
    '',
    'fn add(a,b)',
    'return a+b',
    'end',
    '',
    'async fn fetch(url)',
    'let r=await http.get(url)',
    'return r',
    'end',
    '',
    'let sq=fn(x)=>x*x',
    'let double=fn(x)=>x*2',
    '',
    'fn makeCounter()',
    'let count=0',
    'fn increment()',
    'count++',
    'return count',
    'end',
    'return increment',
    'end',
    '',
    'let arr=[1,2,3,4,5]',
    'let nested=[[1,2],[3,4],[5,6]]',
    'let matrix=[',
    '[1,0,0],',
    '[0,1,0],',
    '[0,0,1]',
    ']',
    '',
    'let person={"name":"Riad","age":30}',
    'let config={',
    '"host":"localhost",',
    '"port":8080,',
    '"debug":True',
    '}',
    '',
    'for i in arr',
    'print(i)',
    'if i==3',
    'print("found")',
    'end',
    'end',
    '',
    'let i=0',
    'while i<10',
    'i++',
    'if i==5',
    'break',
    'end',
    'end',
    '',
    'do',
    'print("hello")',
    'i++',
    'while (i<3)',
    '',
    'match x',
    'case 1',
    'print("one")',
    'case 2',
    'print("two")',
    'default',
    'print("other")',
    'end',
    '',
    'try',
    'let y=1/0',
    'catch e',
    'print(e)',
    'finally',
    'print("done")',
    'end',
].join('\n');

const lines = TEST.split('\n');
const doc = { lineCount: lines.length, lineAt: n => ({ text: lines[n] }) };
const out  = formatDocument(doc, { insertSpaces: true, tabSize: 4 }).split('\n');

console.log('=== FORMATTED OUTPUT ===\n');
console.log(out.join('\n'));

const checks = [
    ['class Animal at col 0',          out.some(l => l === 'class Animal')],
    ['init() at 1 indent',             out.some(l => l === '    init(name, age)')],
    ['self.name at 2 indents',         out.some(l => l === '        self.name = name')],
    ['speak() at 1 indent',            out.some(l => l === '    speak()')],
    ['return inside method at 2',      out.some(l => l === '        return self.name')],
    ['async fetchBio at 1 indent',     out.some(l => l === '    async fetchBio(id)')],
    ['await at 2 indents',             out.some(l => l === '        let data = await api.get(id)')],
    ['toString() at 1 indent',         out.some(l => l === '    toString()')],
    ['Dog class at col 0',             out.some(l => l === 'class Dog is Animal')],
    ['Dog speak() at 1 indent',        out.some(l => l === '    speak()')],
    ['Dog async method at 1 indent',   out.some(l => l === '    async fetchBreed(id)')],
    ['fn add at col 0',                out.some(l => l === 'fn add(a, b)')],
    ['return in fn at 1 indent',       out.some(l => l === '    return a + b')],
    ['async fn at col 0',              out.some(l => l === 'async fn fetch(url)')],
    ['await in async fn at 1',         out.some(l => l === '    let r = await http.get(url)')],
    ['arrow fn at col 0',              out.some(l => l === 'let sq = fn(x) => x * x')],
    ['nested fn at 1 indent',          out.some(l => l === '    fn increment()')],
    ['nested fn body at 2 indents',    out.some(l => l === '        count++')],
    ['matrix row at 1 indent',         out.some(l => l.trim() === '[1, 0, 0],')],
    ['closing ] at col 0',             out.some(l => l === ']')],
    ['map key at 1 indent',            out.some(l => l.startsWith('    ') && l.trim().startsWith('"host"'))],
    ['closing } at col 0',             out.some(l => l === '}')],
    ['for body at 1 indent',           out.some(l => l === '    print(i)')],
    ['nested if at 1 indent',          out.some(l => l === '    if i == 3')],
    ['nested if body at 2 indents',    out.some(l => l === '        print("found")')],
    ['while at col 0',                 out.some(l => l === 'while i < 10')],
    ['while body at 1 indent',         out.some(l => l === '    i++')],
    ['do at col 0',                    out.some(l => l === 'do')],
    ['do body at 1 indent',            out.some(l => l === '    print("hello")')],
    ['do-while closer at col 0',       out.some(l => l === 'while (i < 3)')],
    ['match at col 0',                 out.some(l => l === 'match x')],
    ['case at 1 indent',               out.some(l => l === '    case 1')],
    ['case body at 2 indents',         out.some(l => l === '        print("one")')],
    ['default at 1 indent',            out.some(l => l === '    default')],
    ['default body at 2 indents',      out.some(l => l === '        print("other")')],
    ['try at col 0',                   out.some(l => l === 'try')],
    ['try body at 1 indent',           out.some(l => l === '    let y = 1 / 0')],
    ['catch at col 0',                 out.some(l => l === 'catch e')],
    ['catch body at 1 indent',         out.some(l => l === '    print(e)')],
    ['finally at col 0',               out.some(l => l === 'finally')],
    ['finally body at 1 indent',       out.some(l => l === '    print("done")')],
];

console.log('\n=== CHECKS ===');
let passed = 0;
for (const [label, ok] of checks) {
    console.log((ok ? '✅' : '❌') + ' ' + label);
    if (ok) passed++;
}
console.log(`\n${passed}/${checks.length} passed`);
