const DJAZAIR_DOCS = {
    // Global Functions
    'print': { sig: 'print(value, ...)', desc: 'Prints the given values to the standard output.' },
    'input': { sig: 'input(prompt)', desc: 'Reads a line of input from the user with an optional prompt string.' },
    'type': { sig: 'type(value)', desc: 'Returns a string representing the type of the value.' },
    'str': { sig: 'str(value)', desc: 'Converts a value to its string representation.' },
    'int': { sig: 'int(value)', desc: 'Converts a value to an integer.' },
    'num': { sig: 'num(value)', desc: 'Converts a value to a number.' },
    'float': { sig: 'float(value)', desc: 'Converts a value to a floating-point number.' },
    'bool': { sig: 'bool(value)', desc: 'Converts a value to a boolean.' },
    'isNull': { sig: 'isNull(value)', desc: 'Returns true if the value is null.' },
    'isString': { sig: 'isString(value)', desc: 'Returns true if the value is a string.' },
    'isNumber': { sig: 'isNumber(value)', desc: 'Returns true if the value is a number.' },
    'isBool': { sig: 'isBool(value)', desc: 'Returns true if the value is a boolean.' },
    'isArray': { sig: 'isArray(value)', desc: 'Returns true if the value is an array.' },
    'isMap': { sig: 'isMap(value)', desc: 'Returns true if the value is a map/dictionary.' },
    'isFunction': { sig: 'isFunction(value)', desc: 'Returns true if the value is a function.' },
    'isClass': { sig: 'isClass(value)', desc: 'Returns true if the value is a class.' },
    'isInstance': { sig: 'isInstance(value, class)', desc: 'Returns true if the value is an instance of the class.' },
    'chr': { sig: 'chr(value)', desc: 'Returns the character representing the given Unicode code point.' },
    'ord': { sig: 'ord(char)', desc: 'Returns the Unicode code point for the given character.' },
    'exit': { sig: 'exit(code)', desc: 'Exits the program with the given status code.' },
    'has': { sig: 'has(obj, key)', desc: 'Checks if an object or map has the specified key/property.' },
    'abs': { sig: 'abs(value)', desc: 'Returns the absolute value of a number.' },
    'round': { sig: 'round(value)', desc: 'Rounds a number to the nearest integer.' },
    'enumerate': { sig: 'enumerate(iterable)', desc: 'Returns an array of [index, value] pairs for the iterable.' },
    'range': { sig: 'range(start, end, step?)', desc: 'Generates an array of numbers from start to end.' },
    'zip': { sig: 'zip(arr1, arr2)', desc: 'Zips two arrays together into an array of pairs.' },
    'getLine': { sig: 'getLine()', desc: 'Returns the current execution line number.' },
    'getFile': { sig: 'getFile()', desc: 'Returns the current execution file path.' },
    'getDir': { sig: 'getDir()', desc: 'Returns the current execution directory path.' },

    // Array Methods
    'length': { sig: 'length()', desc: 'Returns the number of elements in the collection/string.' },
    'append': { sig: 'append(value)', desc: 'Adds an element to the end of the array.' },
    'pop': { sig: 'pop()', desc: 'Removes and returns the last element of the array or map.' },
    'insert': { sig: 'insert(index, value)', desc: 'Inserts an element at the specified index.' },
    'remove': { sig: 'remove(value)', desc: 'Removes the first occurrence of the value.' },
    'reverse': { sig: 'reverse()', desc: 'Reverses the array or string in place (or returns reversed).' },
    'index': { sig: 'index(value)', desc: 'Returns the index of the first occurrence of the value.' },
    'extend': { sig: 'extend(arr)', desc: 'Extends the array by appending elements from another array.' },
    'sort': { sig: 'sort()', desc: 'Sorts the array in place.' },
    'copy': { sig: 'copy()', desc: 'Returns a shallow copy of the array or map.' },
    'clear': { sig: 'clear()', desc: 'Removes all elements from the array or map.' },
    'contains': { sig: 'contains(value)', desc: 'Returns true if the collection contains the value.' },
    'count': { sig: 'count(value)', desc: 'Returns the number of occurrences of the value.' },
    'concat': { sig: 'concat(other)', desc: 'Returns a new array/string by concatenating with another.' },
    'slice': { sig: 'slice(start, end?)', desc: 'Returns a sub-array or sub-string.' },
    'join': { sig: 'join(separator)', desc: 'Joins array elements into a string using the separator.' },
    'flatten': { sig: 'flatten()', desc: 'Returns a flattened 1D array.' },
    'unique': { sig: 'unique()', desc: 'Returns a new array with duplicate elements removed.' },
    'sum': { sig: 'sum()', desc: 'Returns the sum of all elements in the array.' },
    'max': { sig: 'max()', desc: 'Returns the maximum value in the array.' },
    'min': { sig: 'min()', desc: 'Returns the minimum value in the array.' },
    'all': { sig: 'all()', desc: 'Returns true if all elements in the array are truthy.' },
    'any': { sig: 'any()', desc: 'Returns true if any element in the array is truthy.' },
    'filter': { sig: 'filter(fn)', desc: 'Returns a new array with elements that pass the test function.' },
    'map': { sig: 'map(fn)', desc: 'Returns a new array with the results of calling the function on every element.' },
    'reduce': { sig: 'reduce(fn, initial?)', desc: 'Reduces the array to a single value using the reducer function.' },
    'find': { sig: 'find(fn)', desc: 'Returns the first element that satisfies the provided testing function.' },
    'every': { sig: 'every(fn)', desc: 'Returns true if all elements pass the test function.' },
    'some': { sig: 'some(fn)', desc: 'Returns true if at least one element passes the test function.' },

    // Map Methods
    'get': { sig: 'get(key, default?)', desc: 'Returns the value for the key, or default if not found.' },
    'keys': { sig: 'keys()', desc: 'Returns an array of all keys in the map.' },
    'values': { sig: 'values()', desc: 'Returns an array of all values in the map.' },
    'items': { sig: 'items()', desc: 'Returns an array of [key, value] pairs for the map.' },
    'setDefault': { sig: 'setDefault(key, default)', desc: 'Returns the value of the key. If not present, sets it to default and returns it.' },
    'update': { sig: 'update(map)', desc: 'Updates the map with key-value pairs from another map.' },

    // String Methods
    'capitalize': { sig: 'capitalize()', desc: 'Returns a copy of the string with its first character capitalized.' },
    'center': { sig: 'center(width)', desc: 'Returns a centered string of the given width.' },
    'charCodeAt': { sig: 'charCodeAt(index)', desc: 'Returns the Unicode value of the character at the given index.' },
    'endsWith': { sig: 'endsWith(str)', desc: 'Returns true if the string ends with the specified substring.' },
    'startsWith': { sig: 'startsWith(str)', desc: 'Returns true if the string starts with the specified substring.' },
    'isAlpha': { sig: 'isAlpha()', desc: 'Returns true if all characters are alphabetic.' },
    'isAlnum': { sig: 'isAlnum()', desc: 'Returns true if all characters are alphanumeric.' },
    'isDigit': { sig: 'isDigit()', desc: 'Returns true if all characters are digits.' },
    'isLower': { sig: 'isLower()', desc: 'Returns true if all characters are lowercase.' },
    'isUpper': { sig: 'isUpper()', desc: 'Returns true if all characters are uppercase.' },
    'isSpace': { sig: 'isSpace()', desc: 'Returns true if all characters are whitespace.' },
    'lower': { sig: 'lower()', desc: 'Returns a copy of the string converted to lowercase.' },
    'upper': { sig: 'upper()', desc: 'Returns a copy of the string converted to uppercase.' },
    'strip': { sig: 'strip()', desc: 'Returns a copy of the string with leading and trailing whitespace removed.' },
    'lStrip': { sig: 'lStrip()', desc: 'Returns a copy of the string with leading whitespace removed.' },
    'rStrip': { sig: 'rStrip()', desc: 'Returns a copy of the string with trailing whitespace removed.' },
    'replace': { sig: 'replace(old, new)', desc: 'Returns a copy of the string with all occurrences of substring old replaced by new.' },
    'split': { sig: 'split(separator)', desc: 'Splits the string into an array of substrings using the separator.' },
    'subStr': { sig: 'subStr(start, length)', desc: 'Returns a substring beginning at start with the given length.' },

    // Keywords
    'fn': { sig: 'Keyword', desc: 'Defines a function.' },
    'async': { sig: 'Keyword', desc: 'Defines an asynchronous function or method.' },
    'await': { sig: 'Keyword', desc: 'Pauses execution until the asynchronous operation completes.' },
    'let': { sig: 'Keyword', desc: 'Declares a local variable.' },
    'return': { sig: 'Keyword', desc: 'Exits a function and optionally returns a value.' },
    'if': { sig: 'Keyword', desc: 'Starts a conditional statement.' },
    'elif': { sig: 'Keyword', desc: 'Adds an else-if branch to a conditional statement.' },
    'else': { sig: 'Keyword', desc: 'Executes a block of code if the condition is false.' },
    'for': { sig: 'Keyword', desc: 'Starts a for loop, usually over an iterable (e.g., `for x in arr`).' },
    'while': { sig: 'Keyword', desc: 'Starts a while loop that executes as long as the condition is true.' },
    'do': { sig: 'Keyword', desc: 'Starts a do-while loop.' },
    'match': { sig: 'Keyword', desc: 'Starts a pattern matching statement.' },
    'case': { sig: 'Keyword', desc: 'Defines a case branch in a match statement.' },
    'default': { sig: 'Keyword', desc: 'Defines the default branch in a match statement.' },
    'try': { sig: 'Keyword', desc: 'Starts a block of code to test for errors.' },
    'catch': { sig: 'Keyword', desc: 'Catches and handles errors thrown in a try block.' },
    'finally': { sig: 'Keyword', desc: 'Executes a block of code regardless of whether an error was thrown.' },
    'end': { sig: 'Keyword', desc: 'Marks the end of a block (e.g., fn, class, if, while, for).' },
    'class': { sig: 'Keyword', desc: 'Defines a new class.' },
    'is': { sig: 'Keyword', desc: 'Used in class definitions for inheritance (e.g., `class Dog is Animal`).' },
    'self': { sig: 'Keyword', desc: 'Refers to the current instance within a class method.' },
    'init': { sig: 'Keyword', desc: 'Constructor method for a class, called when an instance is created.' },
    'break': { sig: 'Keyword', desc: 'Exits a loop prematurely.' },
    'continue': { sig: 'Keyword', desc: 'Skips the rest of the current loop iteration and moves to the next.' },
    'import': { sig: 'Keyword', desc: 'Imports a module or file.' },
    'from': { sig: 'Keyword', desc: 'Specifies the source module to import from.' },
    'in': { sig: 'Keyword', desc: 'Used in a for loop to iterate over elements.' },
    'True': { sig: 'Keyword', desc: 'The boolean truth value.' },
    'False': { sig: 'Keyword', desc: 'The boolean false value.' },
    'Null': { sig: 'Keyword', desc: 'Represents the intentional absence of any value.' },
    'as': { sig: 'Keyword', desc: 'Used for aliasing imports.' },
    'instanceof': { sig: 'Keyword', desc: 'Checks if an object is an instance of a specific class.' },
    'new': { sig: 'Keyword', desc: 'Creates a new instance of a class.' },
    'throw': { sig: 'Keyword', desc: 'Throws an exception or error.' },
    'use': { sig: 'Keyword', desc: 'Uses a namespace or trait.' },
    'super': { sig: 'Keyword', desc: 'Refers to the parent class.' }
};

// Hybrid modules (C + Djazair): registered in std_registry.c
// Pure Djazair modules: loaded dynamically at runtime
// Both are valid and usable via `use <module>`
const DJAZAIR_MODULES = [
    // Hybrid (C-native)
    'crypto', 'datetime', 'dir', 'env', 'file',
    'json', 'lang', 'math', 'net', 'os',
    'process', 'random', 'regex', 'thread',
    // Pure Djazair (dynamically loaded)
    'assert', 'bytes', 'collections', 'http', 'path', 'uuid'
];

const GLOBAL_FUNCTIONS = [
    'print', 'input', 'type', 'str', 'int', 'num', 'float', 'bool', 'isNull',
    'isString', 'isNumber', 'isBool', 'isArray', 'isMap', 'isFunction', 'isClass',
    'isInstance', 'chr', 'ord', 'exit', 'has', 'abs', 'round', 'enumerate', 'range',
    'zip', 'getLine', 'getFile', 'getDir'
];

module.exports = { DJAZAIR_DOCS, DJAZAIR_MODULES, GLOBAL_FUNCTIONS };
